-- Add migration script here
-- Create Enum
CREATE TYPE "hardware_type" AS ENUM ('Keyboard', 'Mouse', 'Microphone', 'Headset');
-- Create Table
CREATE TABLE IF NOT EXISTS presets (
  preset_id uuid DEFAULT gen_random_uuid(),
  name text not null,
  created_on timestamp with time zone not null default (now() at time zone 'utc'::text),
  last_updated_on timestamp with time zone null,
  download_url text not null,
  description text not null default ''::text,
  youtube_id text null,
  photo_url text null,
  hardware hardware_type not null,
  views numeric not null default '0'::numeric,
  downloads bigint not null default '0'::bigint,
  constraint presets_pkey primary key (preset_id),
  constraint presets_description_check check ((length(description) <= 600))
);
-- Create Table
CREATE TABLE IF NOT EXISTS games (
  game_id bigint generated by default as identity,
  preset_id uuid not null,
  game_name text not null,
  created_at timestamp with time zone not null default now(),
  constraint games_pkey primary key (game_id),
  constraint games_preset_id_fkey foreign key (preset_id) references presets (preset_id) on update cascade on delete cascade
);
-- Create Table
CREATE TABLE IF NOT EXISTS downloads (
  download_id bigint generated by default as identity,
  preset_id uuid not null,
  ip_addr varchar(15) not null,
  created_on timestamp with time zone not null default (now() at time zone 'utc'::text),
  constraint downloads_pkey primary key (download_id),
  constraint downloads_download_id_key unique (download_id),
  constraint downloads_preset_id_fkey foreign key (preset_id) references presets (preset_id) on update cascade on delete cascade
);
-- Create Table
CREATE TABLE IF NOT EXISTS comments (
  comment_id bigint generated by default as identity,
  preset_id uuid not null,
  ip_addr varchar(15) not null,
  text text not null default ''::text,
  created_at timestamp with time zone not null default now(),
  constraint comment_pkey primary key (comment_id),
  constraint comments_preset_id_fkey foreign key (preset_id) references presets (preset_id) on update cascade on delete cascade
);